db:
  image: tecris.org:5000/mysql57
  hostname: db
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=mysql
  - MYSQL_USER=bookstore
  - MYSQL_PASSWORD=1bookstore!
  - MYSQL_DATABASE=bookstore

web:
  image: tecris.org:5000/tomcat8-ds
  hostname: web
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "8080:8080"
  links:
  - db
