registry:
  container_name: registry2
  restart: always
  image: registry:2
  ports:
    - 172.17.0.1:443:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    # how to override configuration
    # https://docs.docker.com/registry/configuration/#override-specific-configuration-options
    # https://github.com/docker/distribution/blob/master/docs/configuration.md
    REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
  volumes:
    - /opt/docker_volumes/registry/data:/var/lib/registry
    - /opt/docker_volumes/registry/certs:/certs
