db:
  image: tecris.org:5000/mysql56
  hostname: db
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=mysql
  - MYSQL_USER=bookstore
  - MYSQL_PASSWORD=1bookstore!
  - MYSQL_DATABASE=bookstoredb

web:
  image: tecris.org:5000/wildfly4mysql
  hostname: web
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "8080:8080"
  - "9990:9990"
  links:
  - db
