apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  publicIPs:
    - 172.30.17.100
  ports:
    # the port that this service should serve on
    - port: 5432
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: postgres

