# cat tomcat.yaml 
apiVersion: v1beta3
kind: Pod
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  containers:
    - resources:
        limits :
          cpu: 1
      image: tecris.org:5000/omstomcat
      name: tomcat
      ports:
        - containerPort: 8080
          name: tomcat

