db:
  image: casadocker/mysql:5.7
  hostname: flyway-demo
  container_name: mysql-planets-db
  stdin_open: true
  tty: true
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=mysql
  - MYSQL_USER=book
  - MYSQL_PASSWORD=1book!
  - MYSQL_DATABASE=bookstoredb
