apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: db
  name: db
spec:
  ports:
    # the port that this service should serve on
    - port: 5432
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: db


