# cat postgres.yaml 
apiVersion: v1beta3
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
    - resources:
        limits :
          cpu: 1
      image: tecris.org:5000/omsdb
      name: postgres
      ports:
        - containerPort: 5432
          name: postgres

